version: '3.9'
services:
  postgresdb:
    image: postgres:latest
    ports:
      - '6500:5432'
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - ./.env
  nextjs:
    build: ./
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - /.env
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb
volumes:
  data:
  bindmount: